const Actions = {
    ADD_TODO: 'ADD_TODO',
    CLEAR_DESCRIPTION: 'CLEAR_DESCRIPTION',
    MARK_AS_DONE: 'MARK_AS_DONE',
    MARK_AS_PENDING: 'MARK_AS_PENDING',
    SEARCH: 'SEARCH',
    SET_DESCRIPTION: 'SET_DESCRIPTION',
}

export default Actions;
